### ISSUE TITLE
Port optional?

### ISSUE THREAD

**Issue by fabianfisahn** [panaaj/signalk-client-angular#1]
Is it possible to change the port as an optional parameter for the "connect" and "connectStream" methods? 
I'll try to connect to https://demo.signalk.org which isn't working because I can't leave the port empty because it will be 3000 by default.

Thank you
Fabian

**Comment by panaaj** [comment]
The `connect` function accepts the following parameters.... using port 80 would solve your issue.

```javascript
  connect(
    hostname, // hostname / ip address,
    port,     // (default to 3000 if not supplied)
    useSSL    // true or false (default)
  )
```

The connectStream function also accepts these parameters andin addition a subscription.
```
connectStream(
    hostname, // hostname / ip address,
    port,     // (default to 3000 if not supplied)
    useSSL,    // true or false (default)
    subscribe  // subscription string 
  )
```

**Comment by fabianfisahn** [comment]
That's what I thought and tried. I might be a special config of the demo server.

When I use

this.httpClient.get('https://demo.signalk.org/signalk').subscribe((data) => {
      console.log(data);
})

it works. But only if because there is no port given.
"connect" and "connectStream" with port 80 or 443 are not working.

**Comment by panaaj** [comment]
This appears to be Cross Origin issue.....

`Access to XMLHttpRequest at 'https://demo.signalk.io/signalk' from origin 'http://localhost:4200' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.`

`credentials:include` is used when making requests to the server, and is done to avoid having to authenticate to the server multiple times (if you have already logged in).

You can easily set up a server locally using docker to try things out.

**Comment by fabianfisahn** [comment]
Ok, no worries. I have a local dev server running but just wanted to test something from the outside.
